name       : python-isort
version    : 4.3.21.2
release    : 4
source     :
    - https://github.com/timothycrosley/isort/archive/4.3.21-2.tar.gz : d3bb35ff6cd1a33104f7325af49abd757fc26901501e11dd9d6e52e7accc18fa
license    : MIT
component  : programming.python
summary    : A Python utility / library to sort imports.
description: |
    A Python utility / library to sort imports.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-futures
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
