name       : python-isort
version    : 4.2.15
release    : 2
source     :
    - https://github.com/timothycrosley/isort/archive/4.2.15.tar.gz : 46c1ba5d7152822fe76e04ed571a1d97b25f5328bab547663e7480ead599c732
license    : MIT
component  : programming.python
summary    : A Python utility / library to sort imports.
description: |
    A Python utility / library to sort imports.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
