name       : python-isort
version    : 5.11.4
release    : 12
source     :
    - https://pypi.io/packages/source/i/isort/isort-5.11.4.tar.gz : 6db30c5ded9815d813932c04c2f85a360bcdd35fed496f4d8f35495ef0a261b6
homepage   : https://pycqa.github.io/isort/
license    : MIT
component  : programming.python
summary    : A Python utility / library to sort imports.
description: |
    isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type. It provides a command line utility, Python library and plugins for various editors to quickly sort all your imports.
#builddeps  :
#    - python-black      # check
#    - python-colorama   # check
#    - python-hypothesis # check
#    - python-pytest     # check
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # required packaging python-pylama python-libcst python-hypothesmith
#    %python3_test pytest3 -k 'not test_format and not test_pylama_isort and not test_hypothesmith'
