name       : python-isort
version    : 5.5.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/48/0f/6891366ea99c001dfa69901f6c40c745d8acc524d7c26c0f8f8b666dc420/isort-5.5.1.tar.gz : 92533892058de0306e51c88f22ece002a209dc8e80288aa3cec6d443060d584f
license    : MIT
component  : programming.python
summary    : A Python utility / library to sort imports.
description: |
    A Python utility / library to sort imports.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
