name       : python-isort
version    : 5.10.1
release    : 11
source     :
    - https://pypi.io/packages/source/i/isort/isort-5.10.1.tar.gz : e8443a5e7a020e9d7f97f1d7d9cd17c88bcb3bc7e218bf9cf5095fe550be2951
homepage   : https://pycqa.github.io/isort/
license    : MIT
component  : programming.python
summary    : A Python utility / library to sort imports.
description: |
    isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type. It provides a command line utility, Python library and plugins for various editors to quickly sort all your imports.
builddeps  :
    - python-black      # check
    - python-colorama   # check
    - python-hypothesis # check
    - python-pytest     # check
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -k 'not test_format and not test_pylama_isort and not test_hypothesmith'
